In [1]:
import pandas as pd
import requests

In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.chrome.options import Options

In [31]:
options = Options()
options.page_load_strategy = 'normal'
driver = webdriver.Chrome(options=options)

In [32]:
def get_links(url):
    
    driver.get(url)

    root_div1 = driver.find_element(By.XPATH, "//*[@id='main-container']/div[5]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]")
    child_divs1 = root_div1.find_elements(By.XPATH, "./div")

    no_of_matches = len(child_divs1) + 1
    links = []

    for i in range(1, no_of_matches):
        link_xpath = "//*[@id='main-container']/div[5]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[" + str(i) + "]/div[1]/div[2]/a"
        link = driver.find_element(By.XPATH, link_xpath).get_attribute("href")
        links.append(link)
    
    modified_links = [link.replace('full-scorecard', 'match-overs-comparison') for link in links]
    
    return modified_links

In [33]:
def over_by_over_summary(modified_links, year):
    
    details = []
    team1s = []
    team2s = []
    team1_total_scores = []
    team2_total_scores = []
    winning_details = []
    overs = []
    runs_after_overs = []
    runs_in_overs = []
    batting_teams = []
    bowling_teams = []
    years = []

    for link in modified_links:
        driver.get(link)

        try:
            detail_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]"
            detail = driver.find_element(By.XPATH, detail_xpath).text
        except Exception as e:
            print("skipped at detail")
            continue

        try:
            team1_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]/span[1]"
            team1 = driver.find_element(By.XPATH, team1_xpath).text
        except Exception as e:
            print("skipped at team1")
            continue

        try:
            team2_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/a[1]/span[1]"
            team2 = driver.find_element(By.XPATH, team2_xpath).text
        except Exception as e:
            print("skipped at team2")
            continue

        try:
            team1_total_score_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/strong[1]"
            team1_total_score = driver.find_element(By.XPATH, team1_total_score_xpath).text
        except Exception as e:
            print("skipped at team1_total_score")
            continue

        try:
            team2_total_score_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/strong[1]"
            team2_total_score = driver.find_element(By.XPATH, team2_total_score_xpath).text
        except Exception as e:
            print("skipped at team2_total_score")
            continue

        try:
            winning_detail_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/p[1]/span[1]"
            winning_detail = driver.find_element(By.XPATH, winning_detail_xpath).text
        except Exception as e:
            print("skipped at winning_detail")
            continue

        for i in range(1, 51):
            years.append(year)
            details.append(detail)
            team1s.append(team1)
            team2s.append(team2)
            batting_teams.append(team1)
            bowling_teams.append(team2)
            team1_total_scores.append(team1_total_score)
            team2_total_scores.append(team2_total_score)
            winning_details.append(winning_detail)

            try:
                over_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/table/tbody/tr[" + str(i) + "]/td[1]/div[1]"
                over = driver.find_element(By.XPATH, over_xpath).text
                overs.append(over)
            except Exception as e:
                overs.append('')

            try:
                runs_after_over_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/table/tbody/tr[" + str(i) + "]/td[2]/div[1]/div[1]/div[1]"
                runs_after_over = driver.find_element(By.XPATH, runs_after_over_xpath).text
                runs_after_overs.append(runs_after_over)
            except Exception as e:
                runs_after_overs.append('')

            try:
                runs_in_over_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/table/tbody/tr[" + str(i) + "]/td[2]/div[1]/div[1]/div[1]/span[1]"
                runs_in_over = driver.find_element(By.XPATH, runs_in_over_xpath).text
                runs_in_overs.append(runs_in_over)
            except Exception as e:
                runs_in_overs.append('')


        for i in range(1, 51):
            years.append(year)
            details.append(detail)
            team1s.append(team1)
            team2s.append(team2)
            batting_teams.append(team2)
            bowling_teams.append(team1)
            team1_total_scores.append(team1_total_score)
            team2_total_scores.append(team2_total_score)
            winning_details.append(winning_detail)

            try:
                over_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/table/tbody/tr[" + str(i) + "]/td[1]/div[1]"
                over = driver.find_element(By.XPATH, over_xpath).text
                overs.append(over)
            except Exception as e:
                overs.append('')

            try:
                runs_after_over_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/table/tbody/tr[" + str(i) + "]/td[3]/div[1]/div[1]/div[1]"
                runs_after_over = driver.find_element(By.XPATH, runs_after_over_xpath).text
                runs_after_overs.append(runs_after_over)
            except Exception as e:
                runs_after_overs.append('')

            try:
                runs_in_over_xpath = "//*[@id='main-container']/div[5]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/table/tbody/tr[" + str(i) + "]/td[3]/div[1]/div[1]/div[1]/span[1]"
                runs_in_over = driver.find_element(By.XPATH, runs_in_over_xpath).text
                runs_in_overs.append(runs_in_over)
            except Exception as e:
                runs_in_overs.append('')



    data = {
        'Year' : years,
        'Match Detail' : details,
        'Team 1': team1s,
        'Team 2': team2s,
        'Total Score for Team 1' : team1_total_scores,
        'Total Score for Team 2' : team2_total_scores,
        'Winning Details' : winning_details,
        'Batting team': batting_teams,
        'Bowling team' : bowling_teams,
        'Over Number' : overs,
        'Runs Scored in over' : runs_in_overs,
        'Runs Scored till that over' : runs_after_overs
    }

    df = pd.DataFrame(data)
    
    return df

In [34]:
world_cup_links = {
    2023 : "https://www.espncricinfo.com/series/icc-cricket-world-cup-2023-24-1367856/match-schedule-fixtures-and-results",
    2019 : "https://www.espncricinfo.com/series/icc-cricket-world-cup-2019-1144415/match-schedule-fixtures-and-results",
    2015 : "https://www.espncricinfo.com/series/icc-cricket-world-cup-2014-15-509587/match-schedule-fixtures-and-results",
    2011 : "https://www.espncricinfo.com/series/icc-cricket-world-cup-2010-11-381449/match-schedule-fixtures-and-results",
    2007 : "https://www.espncricinfo.com/series/icc-world-cup-2006-07-125929/match-schedule-fixtures-and-results",
}

In [35]:
df = pd.DataFrame()
for year, link in world_cup_links.items():
    modified_links = get_links(link)
    dftemp = over_by_over_summary(modified_links, year)
    df = pd.concat([df, dftemp], ignore_index = True)
    df

skipped at team1_total_score
skipped at team2_total_score
skipped at team1_total_score
skipped at team1_total_score
skipped at team1_total_score
skipped at team2_total_score

In [36]:
df

,Year,Match Detail,Team 1,Team 2,Total Score for Team 1,Total Score for Team 2,Winning Details,Batting team,Bowling team,Over Number,Runs Scored in over,Runs Scored till that over
0,2023,"1st Match (D/N), Ahmedabad, October 05, 2023,\...",ENG,NZ,282/9,283/1,New Zealand won by 9 wickets (with 82 balls re...,ENG,NZ,1,"(12 runs, 0 wkt)","12/0(12 runs, 0 wkt)"
1,2023,"1st Match (D/N), Ahmedabad, October 05, 2023,\...",ENG,NZ,282/9,283/1,New Zealand won by 9 wickets (with 82 balls re...,ENG,NZ,2,"(0 runs, 0 wkt)","12/0(0 runs, 0 wkt)"
2,2023,"1st Match (D/N), Ahmedabad, October 05, 2023,\...",ENG,NZ,282/9,283/1,New Zealand won by 9 wickets (with 82 balls re...,ENG,NZ,3,"(4 runs, 0 wkt)","16/0(4 runs, 0 wkt)"
3,2023,"1st Match (D/N), Ahmedabad, October 05, 2023,\...",ENG,NZ,282/9,283/1,New Zealand won by 9 wickets (with 82 balls re...,ENG,NZ,4,"(5 runs, 0 wkt)","21/0(5 runs, 0 wkt)"
4,2023,"1st Match (D/N), Ahmedabad, October 05, 2023,\...",ENG,NZ,282/9,283/1,New Zealand won by 9 wickets (with 82 balls re...,ENG,NZ,5,"(5 runs, 0 wkt)","26/0(5 runs, 0 wkt)"
...,...,...,...,...,...,...,...,...,...,...,...,...
23895,2007,"Final, Bridgetown, April 28, 2007,\nICC World Cup",AUS,SL,281/4,215/8,Australia won by 53 runs (D/L method),SL,AUS,,,
23896,2007,"Final, Bridgetown, April 28, 2007,\nICC World Cup",AUS,SL,281/4,215/8,Australia won by 53 runs (D/L method),SL,AUS,,,
23897,2007,"Final, Bridgetown, April 28, 2007,\nICC World Cup",AUS,SL,281/4,215/8,Australia won by 53 runs (D/L method),SL,AUS,,,
23898,2007,"Final, Bridgetown, April 28, 2007,\nICC World Cup",AUS,SL,281/4,215/8,Australia won by 53 runs (D/L method),SL,AUS,,,
23899,2007,"Final, Bridgetown, April 28, 2007,\nICC World Cup",AUS,SL,281/4,215/8,Australia won by 53 runs (D/L method),SL,AUS,,,

In [37]:
df.replace('', pd.NA, inplace=True)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23900 entries, 0 to 23899
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        23900 non-null  int64
 1   Match Detail                23900 non-null  object
 2   Team 1                      23900 non-null  object
 3   Team 2                      23900 non-null  object
 4   Total Score for Team 1      23900 non-null  object
 5   Total Score for Team 2      23900 non-null  object
 6   Winning Details             23900 non-null  object
 7   Batting team                23900 non-null  object
 8   Bowling team                23900 non-null  object
 9   Over Number                 22700 non-null  object
 10  Runs Scored in over         21031 non-null  object
 11  Runs Scored till that over  21031 non-null  object
dtypes: int64(1), object(11)
memory usage: 2.2+ MB

In [ ]:
df1 = df.dropna(subset=['Over Number', 'Runs Scored in over', 'Runs Scored till that over'], how='any')

In [29]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21031 entries, 0 to 23885
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Year                        21031 non-null  int64
 1   Match Detail                21031 non-null  object
 2   Team 1                      21031 non-null  object
 3   Team 2                      21031 non-null  object
 4   Total Score for Team 1      21031 non-null  object
 5   Total Score for Team 2      21031 non-null  object
 6   Winning Details             21031 non-null  object
 7   Batting team                21031 non-null  object
 8   Bowling team                21031 non-null  object
 9   Over Number                 21031 non-null  object
 10  Runs Scored in over         21031 non-null  object
 11  Runs Scored till that over  21031 non-null  object
dtypes: int64(1), object(11)
memory usage: 2.1+ MB

In [30]:
df1.to_csv("df.csv")